### ISSUE TITLE
Please explain how to get the moment when test passed/failed

### ISSUE THREAD

**Issue by joemast** [xunit/samples.xunit#14]
My use-case: I need to report about test result to external system, so I need to determine the moment when test is finished and get information about it's status (passed/failed).

Please explain shortly how could I do this? I see the interfaces like ITestPassed but how to deal with them in my case?

**Comment by bradwilson** [comment]
Who is the actor in this case? Are you writing a test runner, or are you using the existing test runners?

**Comment by joemast** [comment]
I use existing test runners (VS, console)

**Comment by joemast** [comment]
Is it possible to catch the moment when test finished (and determine test status) without runner modification?

**Comment by bradwilson** [comment]
This weekend we added pluggable reporter support to the Console, MSBuild, and DNX runners. This is intended to replace the default runner, which typically reports results to the console or the build logger. Examples of uses here are TeamCity (which emits a special kind of output that's read by the TeamCity build system) or AppVeyor (which sends results via HTTP to the reporter).

Does this sound like it would suit your needs?

**Comment by joemast** [comment]
Not really, I guess. As I understand, You developing a full integration of reporting results to specific services (TeamCity, AppVeyor). But what I need is extension point where I could place my own integration with some service (specifically TestLink in my case)

So my use case is:
1. I run tests (via console, msbuild, etc)
2. When every single test is finished, xunit calls my implementation of extension point (some listener or whatever) with test result object, so it is possible in this extension point to get the status of test execution and report it to TestLink (or TestRail, or whatever)

P.S. The example of such extension poins is http://testng.org/javadocs/org/testng/ITestListener.html for TestNG framework. One can implement interface and set this listener with attribute to test class (or base test class)
P.P.S. I use xUnit for functional tests automation (not unit testing) 

Could you give me some clue of how to implement my use-case with xUnit?

**Comment by bradwilson** [comment]
If you don't want to be notified until after all tests are run, then I would suggest you instruct the runner to output XML results (`-xml Filename` for Console and DNX runners, `Xml='Filename'` for the MSBuild runner), and when the runner exits, you can run whatever post-processing you want on that XML file.

**Comment by joemast** [comment]
For me it would be better to have such extension point but your idea is better than nothing. And it answers my question. Thank you Brad. 

P.S. What if I (or someone) implement such extension point? Is it matches the concept of xUnit?

**Comment by bradwilson** [comment]
Given that there is already a standard way to do this, we're unlikely to add this as an extension point. It would unnecessarily complicate the design of the runners.

**Comment by joemast** [comment]
Ok, thank you for your answers Brad
