### ISSUE TITLE
Add AutoRollback sample

### ISSUE THREAD

**Issue by bradwilson** [xunit/samples.xunit#5]

**Comment by jmwnoble** [comment]
I just added this to my helpers - working in xUnit 2
[original extensions class] (https://github.com/paulecoyote/xunit/blob/master/Main/xunit.extensions/AutoRollback/AutoRollbackAttribute.cs)

**Comment by bradwilson** [comment]
Added in 8928587fd88fb16754b22271f626e7dbd13f4160
