### ISSUE TITLE
Solution does not build

### ISSUE THREAD

**Issue by adamralph** [xunit/samples.xunit#6]
In particular, the SpecificationExamples project is based on v1 abstractions so has multiple build failures.

There is also one build failure in the ObservationExample project.

**Comment by jnewkirk** [comment]
Interesting timing - I am working on it at the moment to update it to RC1 and fix various issues.

**Comment by adamralph** [comment]
Ah, good to know!

**Comment by jnewkirk** [comment]
I updated the samples to RC1 and I have uncovered a few issues. The Observation example no longer compiles and needs a bit more work. We also discovered a bug in the TestCollectionOrderer code in xUnit.net that I logged and Brad and I will fix it when we get back together.

**Comment by bradwilson** [comment]
This is fixed now in RC2.

**Comment by adamralph** [comment]
:+1: confirmed - I just tried locally and all works fine (apart from my missing the OLEDB driver from my machine which means the Excel sample can't run).

**Comment by bradwilson** [comment]
Yeah, I have that problem, too. :)
