### ISSUE TITLE
Update [SkippableFact] example to include [SkippableTheory]

### ISSUE THREAD

**Issue by bradwilson** [xunit/samples.xunit#8]
Moved from https://github.com/xunit/xunit/issues/250

**Comment by khellang** [comment]
Would love to see this example :+1:

**Comment by nulltoken** [comment]
Any chance to see this supported? We heavily rely on it (through xUnit 1.9.2) in LibGit2Sharp.

LibGit2Sharp is a cross-platform project, monitored by Travis (Linux/Mac OS X) and AppVeyor (x86/x64).

This feature allows up to dynamically ignore tests that leverage use cases that aren't supported by the underlying platform yet. See below for an example

```csharp
[SkippableTheory]
[InlineData("false", "hey there\n")]
[InlineData("input", "hey there\n")]
[InlineData("true", "hey there\r\n")]
public void CanReadBlobFilteredStream(string autocrlf, string expectedContent)
{
    SkipIfNotSupported(autocrlf);

    var path = SandboxBareTestRepo();
    using (var repo = new Repository(path))
    {
        repo.Config.Set("core.autocrlf", autocrlf);

        var blob = repo.Lookup<Blob>("a8233120f6ad708f843d861ce2b7228ec4e3dec6");

        var contentStream = blob.GetContentStream(new FilteringOptions("foo.txt"));
        Assert.Equal(expectedContent.Length, contentStream.Length);

        using (var tr = new StreamReader(contentStream, Encoding.UTF8))
        {
            string content = tr.ReadToEnd();

            Assert.Equal(expectedContent, content);
        }
    }
}

private static void SkipIfNotSupported(string autocrlf)
{
    InconclusiveIf(() => autocrlf == "true" && Constants.IsRunningOnUnix, "Non-Windows does not support core.autocrlf = true");
}
```

We haven't been able to find a suitable alternative to this feature (As, `Assert.Ignore()` isn't supported either.

One option would be to do the following, but this would be always be seen as a passing test, sending out a confusing message. Indeed, a passing test would either mean:

 - Everything has worked awesomely!
 - Huh... Nothing to see here. I bailed out early.

```csharp
[Theory]
[InlineData("false", "hey there\n")]
[InlineData("input", "hey there\n")]
[InlineData("true", "hey there\r\n")]
public void CanReadBlobFilteredStream(string autocrlf, string expectedContent)
{
    if (NotSupported(autocrlf))
    {
        return;
    }

    var path = SandboxBareTestRepo();
    using (var repo = new Repository(path))
    {
        repo.Config.Set("core.autocrlf", autocrlf);

        var blob = repo.Lookup<Blob>("a8233120f6ad708f843d861ce2b7228ec4e3dec6");

        var contentStream = blob.GetContentStream(new FilteringOptions("foo.txt"));
        Assert.Equal(expectedContent.Length, contentStream.Length);

        using (var tr = new StreamReader(contentStream, Encoding.UTF8))
        {
            string content = tr.ReadToEnd();

            Assert.Equal(expectedContent, content);
        }
    }
}
```

I like very much the clear message that `[SKIP]` emits: *"Not working yet. Eventually will."*

Would there be a way to cleanly emulate this when the preconditions can't be expressed in a static way?

**Comment by bradwilson** [comment]
Sorry, I haven't gotten to the sample yet. :(

**Comment by bradwilson** [comment]
Sample is available: https://github.com/xunit/samples.xunit/tree/master/DynamicSkipExample

**Comment by nulltoken** [comment]
@bradwilson Do you think you could also add a `[SkippableTheory]` sample? I just realized that its mention disappeared from the context when this issue has been migrated from https://github.com/xunit/xunit/issues/250.

Would you prefer me to open a different issue?

**Comment by bradwilson** [comment]
No, I'll just re-open this one until I can get it added.

**Comment by nulltoken** [comment]
@bradwilson Thanks for your responsiveness!

**Comment by bradwilson** [comment]
Sample has been updated: https://github.com/xunit/samples.xunit/blob/fa2bb2147dbf3a49db86371f21094561b8ad2083/DynamicSkipExample/Samples.cs#L30-L45

**Comment by nulltoken** [comment]
Wow. That was fast. Thanks!
